### ISSUE TITLE
[Bala] Loading Profiles Dynamically

### ISSUE THREAD

**Issue by devigned** [devigned/profile-playground#5]
> I don’t see how we are going to load/refer the namespace dynamically according to the profile in your sample (may be that’s the code inside client.cs?)

**Comment by devigned** [comment]
Could you explain your scenario a bit more?

**Comment by johanste** [comment]
If a client application dynamically tries to change its behavior based on profiles supported on the server (potentially using the DLR and/or the dynamic keyword in C#), I didn't see any way to ask for an appropriate client version based on the information returned from the service.

**Comment by devigned** [comment]
I'm closing this issue in favor of https://github.com/devigned/profile-playground/issues/3
