### ISSUE TITLE
No really convenient method for creating types and using them

### ISSUE THREAD

**Issue by markcowl** [devigned/profile-playground#8]
We could take Garrett's suggestion and place the methods on the types as a solution to this.

using either 

client.Compute.models.Obect to create an object, or mathcing up the models and operation types api version namespaces both seem non user-friendly

**Comment by devigned** [comment]
@markcowl can you think of another way? I think Garrett's suggestion of having fat models could work, but I also think that is a big change that would take quite some time to implement.

**Comment by devigned** [comment]
This is closely related to: https://github.com/devigned/profile-playground/issues/7

**Comment by devigned** [comment]
I'm going to close this one in favor of #7
